export const metaKeywords = [
  'Task Management',
  'Project Management',
  'Productivity App',
  'To-Do List',
  'Kanban Board',
  'Collaboration Tool',
  'Workflow Automation',
  'Team Productivity',
  'Task Scheduling',
  'Agile Project Management',
  'Task Tracking',
  'Get Things Done',
  'Task Organizer',
  'Project Planner',
  'Notiqo',
  'Notiqo-ai',
  'Notiqo.com',
  'Notiqo.net',
  'Notiqo.org',
  'Notiqo.in',
  'Notiqo.co',
  'Notiqo.me',
  'Remote Team Management',
  'Workplace Collaboration',
  'Task Automation',
  'Personal Productivity',
  'Work Management',
  'Daily Planner',
  'Goal Setting',
  'Milestone Tracking',
  'Time Management',
  'Project Timeline',
  'Task Prioritization',
  'Team Communication',
  'Project Dashboard',
  'Task Reminders',
  'Recurring Tasks',
  'Subtasks',
  'Checklist App',
  'Workload Management',
  'Task Delegation',
  'Project Templates',
  'Gantt Chart',
  'Scrum Board',
  'Sprint Planning',
  'Bug Tracking',
  'Issue Management',
  'Team Calendar',
  'Shared Workspace',
  'Document Collaboration',
  'File Sharing',
  'Notes App',
  'Meeting Scheduler',
  'Productivity Tracker',
  'Performance Analytics',
  'Progress Reports',
  'Resource Allocation',
  'Workforce Management',
  'Employee Productivity',
  'Remote Work Tools',
  'Online Collaboration',
  'Digital Workspace',
  'Workflow Optimization',
  'Task Comments',
  'Activity Feed',
  'Notifications',
  'User Roles',
  'Permission Management',
  'Custom Workflows',
  'Project Roadmap',
  'Team Goals',
  'OKR Tracking',
  'KPI Dashboard',
  'Time Tracking',
  'Pomodoro Timer',
  'Focus Mode',
  'Task Archive',
  'Task Labels',
  'Color Coding',
  'Priority Matrix',
  'Eisenhower Matrix',
  'Mind Mapping',
  'Idea Board',
  'Brainstorming Tool',
  'Project Budgeting',
  'Expense Tracking',
  'Client Management',
  'CRM Integration',
  'Calendar Sync',
  'Google Calendar Integration',
  'Outlook Integration',
  'Slack Integration',
  'Zapier Integration',
  'API Access',
  'Mobile Productivity',
  'iOS Task App',
  'Android Task App',
  'Desktop Task App',
  'Web Task App',
  'Cloud Productivity',
  'SaaS Productivity',
  'Enterprise Task Management',
  'Small Business Productivity',
  'Freelancer Tools',
  'Startup Productivity',
  'Agile Tools',
  'Scrum Tools',
  'Kanban Tools',
  'Project Collaboration',
  'Team Task List',
  'Personal Task List',
  'Work Task List',
  'Project Sharing',
  'Task Sharing',
  'Task Export',
  'CSV Export',
  'PDF Export',
  'Data Import',
  'Bulk Task Edit',
  'Task Comments',
  'Task Attachments',
  'File Upload',
  'Task History',
  'Activity Log',
  'User Mentions',
  'Task Followers',
  'Task Watchers',
  'Project Members',
  'Workspace Members',
  'Invite Team',
  'Guest Access',
  'Single Sign-On',
  'Two-Factor Authentication',
  'Data Encryption',
  'GDPR Compliance',
  'Data Security',
  'Cloud Backup',
  'Auto Save',
  'Offline Mode',
  'Dark Mode',
  'Custom Themes',
  'Branding',
  'White Label',
  'User Onboarding',
  'Help Center',
  'Live Chat Support',
  'Email Notifications',
  'Push Notifications',
  'In-App Notifications',
  'Product Updates',
  'Feature Requests',
  'User Feedback',
  'Beta Access',
  'Early Access',
  'Productivity Blog',
  'Productivity Tips',
  'Remote Work Blog',
  'Agile Blog',
  'Project Management Blog',
  'Productivity Community',
  'User Community',
  'Forum',
  'Webinars',
  'Online Training',
  'Video Tutorials',
  'Knowledge Base',
  'FAQ',
  'Changelog',
  'Release Notes',
  'Integrations',
  'Marketplace',
  'App Directory',
  'Productivity Extensions',
  'Browser Extension',
  'Chrome Extension',
  'Firefox Extension',
  'Edge Extension',
  'Safari Extension',
  'Productivity Widget',
  'Dashboard Widget',
  'Task Widget',
  'Calendar Widget',
  'Productivity API',
  'Task API',
  'Project API',
  'Workspace API',
  'Automation API',
  'Webhook',
  'Custom Fields',
  'Custom Statuses',
  'Custom Views',
  'Saved Filters',
  'Smart Filters',
  'Advanced Search',
  'Global Search',
  'Quick Add Task',
  'Quick Edit',
  'Bulk Actions',
  'Drag and Drop',
  'Board View',
  'List View',
  'Calendar View',
  'Timeline View',
  'Table View',
  'Gantt View',
  'My Tasks',
  'Assigned Tasks',
  'Completed Tasks',
  'Overdue Tasks',
  'Upcoming Tasks',
  'Today Tasks',
  'Weekly Planner',
  'Monthly Planner',
  'Annual Planner',
  'Personal Goals',
  'Team Goals',
  'Project Goals',
  'Vision Board',
  'Mission Statement',
  'Product Roadmap',
  'Release Planning',
  'Sprint Review',
  'Retrospective',
  'Backlog Management',
  'Task Dependencies',
  'Blocking Tasks',
  'Linked Tasks',
  'Parent Task',
  'Child Task',
  'Subtask Management',
  'Task Templates',
  'Recurring Projects',
  'Recurring Reminders',
  'Personal Dashboard',
  'Team Dashboard',
  'Workspace Dashboard',
  'Productivity Metrics',
  'Efficiency Tracker',
  'Work Habits',
  'Focus Booster',
  'Motivation Tools',
  'Accountability Partner',
  'Productivity Gamification',
  'Rewards System',
  'Leaderboard',
  'Streaks',
  'Daily Check-In',
  'Weekly Review',
  'Monthly Review',
  'Yearly Review',
  'Goal Progress',
  'Habit Tracker',
  'Routine Builder',
  'Personal CRM',
  'Contact Management',
  'Client Portal',
  'Freelance Management',
  'Consultant Tools',
  'Agency Tools',
  'SMB Tools',
  'Enterprise Tools',
  'Startup Tools',
  'Productivity SaaS',
  'Work Management SaaS',
  'Notiqo SaaS',
];
