import type { Metadata } from "next";
import "@/styles/globals.css";
import '@/styles/theme.css';
import GlobalModals from "./providers/global-modals";
import { QueryProvider } from "./providers/query.provider";
import { Toaster } from "@/components/ui/sonner";
import { GlobalProvider } from "./providers/global.provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <GlobalProvider>
         <QueryProvider>
          <Toaster/>
            <GlobalModals/>
            {children}
         </QueryProvider>
         </GlobalProvider>
    </html>
  );
}
